[project]
name = "sink-snooper-stoppinator"
version = "0.1.0"
description = "Code to stop my cat from playing in the sink"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "opencv-python>=4.11.0.86",
]
